export const POST_RECIPES = 'POST_RECIPES'
export const GET_RECIPES = 'GET_RECIPES'
export const GET_DATABASE = 'GET_DATABASE'
export const GET_TYPES = 'GET_TYPES'
export const GET_STATE_ID = 'GET_STATE_ID'

export const GET_RECIPES_ID = 'GET_RECIPES_ID'
export const GET_RECIPES_NAME = 'GET_RECIPES_NAME'
export const FILTER_BY_SEARCHBAR = 'FILTER_BY_SEARCHBAR'